#+title: Socle interministériel des logiciels libres
#+options: toc:1

Le socle interministériel de logiciels libres (SILL) est le catalogue
de référence des logiciels libres recommandés par l’Etat.

Il est construit de façon collaborative par des communautés d’agents
informaticiens de la fonction publique d'État et de la fonction
publique hospitalière.

- La page d'accueil du SILL côté DINUM : [[https://disic.github.io/sill/index.html][disic.github.io/sill]]
- La page d'accueil des groupes MIM : [[https://www.mim-libre.fr/][www.mim-libre.fr]]
- L'ancienne page de présentation du SILL de la [[https://references.modernisation.gouv.fr/socle-logiciels-libres][DINUM]]

Pour toute question, écrire à [[mailto:bastien.guerry@data.gouv.fr][bastien.guerry@data.gouv.fr]] ou à
[[mailto:mim-noyau@listes.etalab.gouv.fr][mim-noyau@listes.etalab.gouv.fr]] pour contacter l'équipe d'animation
des groupes MIM.

* Le SILL 2020

Le SILL 2020 est en préparation sur le site [[https://sill.etalab.gouv.fr][sill.etalab.gouv.fr]].

** Les documents de construction du SILL 2020

Les documents de construction du SILL 2020 sont disponibles via
l'espace de partage https://groupes.mim-libre.fr.  Si vous êtes
référent, vous pouvez obtenir un compte sur cet espace.

Une fois connecté sur cet espace, les documents de préparations sont
accessibles ici :

- [[https://cloud.mim-libre.fr/apps/files/?dir=/Partage%20MIM/MIMO/SILL&fileid=10858][MIMO]]
- [[https://calc.mim-libre.fr/MIMDEV/edit][MIMDEV]]
- [[https://calc.mim-libre.fr/MIMPROD/edit][MIMPROD]]

Le [[https://github.com/DISIC/sill/][dépôt SILL]] contient aussi [[https://github.com/DISIC/sill/blob/master/2020/sill-2020.csv][un fichier csv pour le SILL 2020]] dans
lequel sont régulièrement consolidées les contributions faites sur ces
documents privés.

* Le SILL 2019

Le SILL 2019 est disponible en [[file:2019/][HTML]], [[file:2019/sill-2019.pdf][PDF]], [[file:2019/sill-2019.odt][ODT]], [[file:2019/sill-2019.ods][ODS]] et [[file:2019/sill-2019.csv][CSV]].

Vous pouvez voir la liste des changements depuis 2018 ([[file:2019/sill-diff-2018-2019.odt][ODT]] et [[file:2019/sill-diff-2018-2019.pdf][PDF]]).

Vous pouvez [[ftp://eoleng.ac-dijon.fr/SILL2019/][télécharger l'installateur de LibreOffice MIMO]].

* Les communautés qui construisent le SILL : groupes MIM

Le préfixe "MIM" signifie "Mutualisation interministérielle".

Le SILL est rédigé par deux groupes : le groupe *MIMO* qui se consacre
aux outils de bureautique et le groupe MIMDEVOPS dédié aux outils de
développement et de production.

Chaque groupe se réunit en présentiel et échange régulièrement par
email ; un groupe « noyau » assure la coordination de l'ensemble.

Pour demander à participer aux échanges des groupes :

- s’inscrire sur [[https://listes.etalab.gouv.fr/listinfo/mimo][la liste MIMO]] ;
- s’inscrire sur [[https://listes.etalab.gouv.fr/listinfo/mim-devops][la liste MIMDEVOPS]].

* Les critères d’entrée d’un logiciel dans le SILL

** Un prérequis pour tous les logiciels

Le code source du logiciel est publié sous l'une des licences libres
reconnues par la [[https://www.gnu.org/licenses/license-list.fr.html][Free Software Foundation]] ou l'[[https://opensource.org/licenses][Open Source Initiative]],
sans délai de publication entre le code source et la version
exécutable.

** Deux critères obligatoires pour les logiciels recommandés

- Il existe un agent public de la fonction publique d'État ou
  hospitalière référent pour ce logiciel libre.

- Le logiciel est significativement utilisé dans un organisme public
  de la fonction publique d'État ou hospitalière.

** D’autres informations optionnelles

- Le logiciel est *mûr et actif* : la longévité est constatée, il y a de
  bonnes garanties sur la pérennité et il existe une communauté
  dynamique ainsi qu’une feuille de route.

- Le logiciel est *performant*, il a une bonne couverture fonctionnelle
  par rapport au besoin.

- Pour les outils de bureautique, le *logiciel est multiplateforme*.

- Si pertinent, le *logiciel respecte des normes et des standards*,
  notamment ceux du [[http://references.modernisation.gouv.fr/interoperabilite][RGI]] et du [[https://www.numerique.gouv.fr/publications/rgaa-accessibilite/][RGAA]].

- Le logiciel propose des *facilités d'exploitation* : supervision,
  administration, configuration, sauvegarde, existence d'installeurs,
  d'outils de configuration et de déploiement.

- Le logiciel est *adapté aux besoins des organismes publics* français :
  intégration dans les SI, traduction en français, besoins spécifiques
  aux grands comptes.

- L’un des organismes publics utilisateur ayant un usage significatif
  du logiciel a *publié des informations sur cet usage*.

* Comment ajouter un logiciel libre dans le SILL ?

Pour proposer un nouveau logiciel en vue du SILL 2020, vous pouvez
[[https://github.com/DISIC/sill/issues/new?assignees=bzg&labels=Soumission&template=ajout-logiciel.md&title=Nouveau+logiciel+%3A+][ouvrir un ticket sur le dépôt de travail]].

*Attention*: pour qu’un logiciel entre dans le SILL, il faut qu’un agent
public se porte volontaire pour en être le /référent/ (voir ci-dessous.)

* Que signifie être « référent » d’un logiciel ?

** Vous souhaitez être référent ?

Pour cela, vous pouvez [[https://github.com/DISIC/sill/issues/new/choose][ouvrir un ticket]] sur le dépôt du SILL, demander
de vous inscrire sur la [[https://listes.etalab.gouv.fr/listinfo/sill-mainteneurs][liste de discussion des référents]] ou envoyer
un mail à =bastien.guerry@data.gouv.fr=.

** Qui peut être « référent SILL » ?

Tout agent public travaillant dans un organisme public de la fonction
publique d'État ou hospitalière peut être référent d’un logiciel libre
dont il connaît l’usage au sein de son administration.

** Quels sont les tâches du référent ?

*Le référent :*

1. atteste de l’usage d’un logiciel libre dans son administration ;
2. collecte les informations pertinentes (de la version utilisée à des cas d’usage complets) sur le logiciel ;
3. remonte ces informations aux mainteneurs du [[https://github.com/disic/sill][dépôt SILL]] hébergé par la DINUM - s’il peut, il met à jour ce dépôt directement ;
4. participe une fois par an à l’une des réunions du groupe MIM pertinent (MIMO, MIMPROD ou MIMDEV) ;
5. participe aux discussions entre mainteneurs sur la liste [[https://listes.etalab.gouv.fr/listinfo/sill-mainteneurs][sill-mainteneurs]] ;
6. cherche un référent pour le remplacer s’il venait à ne plus pouvoir être référent.

*Le référent n’est pas :*

- un contact de support pour l’ensemble de l’administration ;
- obligé de rester référent toute l’année ;
- obligé de publier son identité.

* Présentations partagées dans les groupes MIM

- 27/11/2019 (MIMO) : [[https://speakerdeck.com/bluehats/presentation-management-poste-de-travail][Présentation Management Poste de travail]]
- 27/11/2019 (MIMO) : [[https://speakerdeck.com/bluehats/firefox-for-enterprise][Firefox for Entreprise]]
- 27/11/2019 (MIMO) : [[https://speakerdeck.com/bluehats/la-gestion-du-poste-de-travail-temps-reel][La gestion du poste de travail temps réel]]
- 27/11/2019 (MIMO) : [[https://speakerdeck.com/bluehats/nextcloud-le-cloud-alternatif-aux-gafam][Nextcloud - Le cloud alternatif aux GAFAM]]

* Le mouvement =#BlueHats=

Le mouvement #BlueHats a été lancé en décembre 2018 par la DINUM et il
rassemble toutes celles et ceux qui soutiennent le développement et
l'utilisation de logiciels libres dans l'administration publique.

Vous pouvez retrouver [[https://github.com/DISIC/gazette-bluehats][la gazette #BlueHats]] publiée par la DINUM, [[https://infolettres.etalab.gouv.fr/subscribe/bluehats@mail.etalab.studio][vous
y inscrire]] et voir la [[https://github.com/DISIC/evenements-bluehats][documentation sur les événements #BlueHats]].

* Licence du SILL et de ce dépôt

Le SILL est publié par les groupes de mutualisation interministérielle
sous [[https://github.com/etalab/Licence-Ouverte/blob/master/LO.md][licence Ouverte 2.0]].

Ce dépôt est publié sous [[https://github.com/etalab/Licence-Ouverte/blob/master/LO.md][licence Ouverte 2.0]].
